version: '3'

services:
  # hub:
  #   image: selenium/hub:4.1.2
  #   ports:
  #     - '4444:4444'


  chrome:
    image: selenium/standalone-chrome:100.0
    ports:
      - 4444:4444
    restart: always
    # depends_on:
    #   - hub
    # environment:
    #   - HUB_HOST=hub
    #   - HUB_PORT=4444

  jupyterlab:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    working_dir: '/src'
    tty: true
    volumes:
      - ./src:/src
      - ./src/notebooks:/src/notebooks
      - ./src/modules:/src/modules
    ports: 
      - '8080:8080'
    depends_on:
      - chrome
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=''


